application: reintendo
version: 1
runtime: python
api_version: 1

handlers:
  - url: /stylesheets
    static_dir: stylesheets
  - url: /mail
    script: mail.py
    login: admin
  - url: .*
    script: reintendo.py
